services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    container_name: vitesse-mongo

  backend:
    build:
      context: .
      dockerfile: deploy/backend.dockerfile
    ports:
      - "34863:34863"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookkeeping
    depends_on:
      - mongo
    restart: always
    container_name: vitesse-backend

  frontend:
    build:
      context: .
      dockerfile: deploy/frontend.dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    container_name: vitesse-frontend

volumes:
  mongo_data:
